services:
  - type: web
    name: vendor-research-agent
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true 